In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
%cd /content/gdrive/MyDrive

/content/gdrive/MyDrive


In [ ]:
%cd /content/gdrive/MyDrive/classy-sort-yolov5


/content/gdrive/MyDrive/classy-sort-yolov5


In [ ]:
!pip install torch==1.10.0+cu102 torchvision==0.11.0+cu102 torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |██████████████████████████████▎ | 834.1 MB 1.2 MB/s eta 0:00:40tcmalloc: large alloc 1147494400 bytes == 0x3aa92000 @  0x7fb75f198615 0x592b76 0x4df71e 0x59afff 0x515655 0x549576 0x593fce 0x548ae9 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x598e3b 0x511f68 0x598e3b 0x511f68 0x598e3b 0x511f68 0x4bc98a 0x532e76 0x594b72 0x515600 0x549576 0x593fce 0x548ae9 0x5127f1 0x549576 0x593fce 0x5118f8 0x593dd7
     |████████████████████████████████| 881.9 MB 19 kB/s 
     |████████████████████████████████| 23.2 MB 1.3 MB/s 
     |████████████████████████████████| 2.7 MB 35.5 MB/s 
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1+cu113
    Uninstalling torch-1.12.1+cu113:
      Successfully uninstalled torch-1.12.1+cu113
  Attempting uninstall: torchvision
    Found existing installation: torchvisio

In [ ]:
!pip install -r requirements.txt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 177 kB 28.6 MB/s 
     |████████████████████████████████| 12.5 MB 48.5 MB/s 
     |████████████████████████████████| 1.5 MB 57.1 MB/s 
  Created wheel for filterpy: filename=filterpy-1.4.5-py3-none-any.whl size=110474 sha256=3a51d853521bbd7d1a062c6d39959bff2806a27d52b5bfd96980c36d67789dce
  Stored in directory: /root/.cache/pip/wheels/ce/e0/ee/a2b3c5caab3418c1ccd8c4de573d4cbe13315d7e8b0a55fbc2
  Created wheel for lap: filename=lap-0.4.0-cp37-cp37m-linux_x86_64.whl size=1590222 sha256=ca1b6f6ec4ab4ccf1f06e72a8747103e592f6882f2245bf2969ce4f34061aca7
  Stored in directory: /root/.cache/pip/wheels/b1/0b/e3/ef9daf1b5547b56389e42c80c3100f1e6479bf5fd00fd9d6ba
Successfully built filterpy lap
  Attempting uninstall: scikit-image
    Found existing installation: scikit-image 0.18.3
    Uninstalling scikit-image-0.18.3:
      Successfully uninstalled scikit-im

In [ ]:
!pip install matplotlib==3.4.3 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 10.3 MB 28.7 MB/s 
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2


In [ ]:
!import matplotlib
!matplotlib.use('TKAgg')

/bin/bash: import: command not found
/bin/bash: -c: line 0: syntax error near unexpected token `'TKAgg''
/bin/bash: -c: line 0: `matplotlib.use('TKAgg')'


In [ ]:
!python classy_track1.py --source "/content/gdrive/MyDrive/2022-06-22-15-00.mp4" --save-txt --save-img

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
 [     1423.8      817.88      1500.7      914.42           0    -0.36742    -0.86035     -22.802         222]
 [     1572.9       686.6      1679.3      751.86           0     -0.6599     0.24013      2.1974          86]
 [     1821.1      828.25      1899.1      939.81           0     0.39623   -0.062289      33.528          77]
 [     1180.6      56.527      1298.3      163.61           0   -0.066071     0.40288     -81.019          76]
 [     1556.2      457.67      1673.7      579.91           0      1.8943    -0.81119      469.34          75]
 [       1590      932.41      1736.4      1029.8           0     0.47788    -0.17026     -20.574          74]
 [     1262.3      484.48      1376.4      596.38           0     0.15679     0.15242     -56.376          73]
 [     419.12      687.74      485.62      790.16           0  -0.0095436     0.17952     -7.5955          69]
 [     120.77      4.7672      188.86      108.84      